#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

# Version of this package (even if built as a child)
MAJOR = '0'
MINOR = '0'
MICRO = '0'
TRACKER_VERSION = "%s.%s.%s" % (MAJOR, MINOR, MICRO)

# Library version (UNIX style major, minor, micro)
TRACKER_LIB_VERSION = '0.0.0'

APPNAME = 'tracker'
I18N_PACKAGE = 'libtracker'

tracker_sources = [
    'base_pattern.cc',
    'base_pattern_phenomenal_diff.cc',
    'rows_phenomenal_diff.cc',
    'pattern.cc',
    'pattern_phenomenal_diff.cc',
    'track_pattern.cc',
    'track_pattern_phenomenal_diff.cc',
    'midi_track_pattern.cc',
    'midi_track_pattern_phenomenal_diff.cc',
    'audio_track_pattern.cc',
    'audio_track_pattern_phenomenal_diff.cc',
    'midi_region_pattern.cc',
    'midi_region_pattern_phenomenal_diff.cc',
    'midi_notes_pattern.cc',
    'midi_notes_pattern_phenomenal_diff.cc',
    'automation_pattern.cc',
    'automation_pattern_phenomenal_diff.cc',
    'main_automation_pattern.cc',
    'processor_automation_pattern.cc',
    'processor_automation_pattern_phenomenal_diff.cc',
    'track_automation_pattern.cc',
    'track_all_automations_pattern.cc',
    'track_all_automations_pattern_phenomenal_diff.cc',
    'midi_region_automation_pattern.cc',
    'midi_region_automation_pattern_phenomenal_diff.cc',
    'tracker_utils.cc',
]

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    # Library
    if bld.is_defined ('INTERNAL_SHARED_LIBS'):
        obj = bld.shlib(features = 'cxx cxxshlib', source=tracker_sources)
        obj.defines      = [ 'LIBTRACKER_DLL_EXPORTS=1' ]
    else:
        obj = bld.stlib(features = 'cxx cxxstlib', source=tracker_sources)
        obj.cxxflags = [ bld.env['compiler_flags_dict']['pic'] ]
        obj.cflags   = [ bld.env['compiler_flags_dict']['pic'] ]
        obj.defines  = [ ]

    obj.export_includes = ['.']
    obj.includes     = ['.', '..']
    obj.name         = 'libtracker'
    obj.target       = 'tracker'
    obj.vnum         = TRACKER_LIB_VERSION
    obj.install_path = bld.env['LIBDIR']
    obj.defines     += [ 'PACKAGE="' + I18N_PACKAGE + '"' ]
    obj.uselib       = [ 'GLIBMM', 'XML', 'OSX' ]
    obj.use          = [ 'libpbd', 'libmidipp', 'libevoral', 'libtemporal', 'libardour' ]
